### ISSUE TITLE
cannot build ThePiratesGuideToR  (target  bookdown::gitbook)

### ISSUE THREAD

**Issue by slonik-az** [ndphillips/ThePiratesGuideToR#1]
Hi,
I recently discovered ThePiratesGuideToR. I love it, and would like to contribute. Unfortunately, I cannot  compile it. Facing two problems

## (1)  duplicate label 'dance'
When I try to build gitbook version from RStudio (Build->Build Book->bookdown::gitbook) I am getting the error
```
processing file: YaRrr.Rmd
Error in parse_block(g[-1], g[1], params.src) : duplicate label 'dance'
Calls: <Anonymous> ... process_file -> split_file -> lapply -> FUN -> parse_block
Execution halted
Exited with status 1.
```
__Workaround:__  In the files `10-advanceddataframe.Rmd` and `11-plotting.Rmd` I renamed label `dance` to `dance0` and `dance1` respectively. 

## (2)  object 'index' not found
After successfully working around  (1), I am facing another compilation problem which I cannot resolve. Attempts to build `gitbook` result in:
```
Quitting from lines 3182-3188 (YaRrr.Rmd) 
Error in eval(expr, envir, enclos) : object 'index' not found
Calls: <Anonymous> ... eval -> subset -> subset.data.frame -> eval -> eval
Execution halted
Exited with status 1.
```
The offending R code (lines 3182-3188) in `YaRrr.Rmd` is:
```{r}
# Get rows of ToothGrowth where len > 30 AND supp == "VC", but only return the len and index columns

subset(x = ToothGrowth,
      subset = len > 30 &
               supp == "VC",
      select = c(len, index))
```
I am on MacOSX El Capitan, using the latest RStudio-1.0.136, latest R-3.3.3, the latest github version of `yarrr` package (the CRAN version of yarrr gives the same errors).  
_Any help is greatly appreciated!_

-- Leo

**Comment by ndphillips** [comment]
Hi @slonik-az  Thanks for the note! I just realised that I hasn't pushed an update to the book in a while. I just pushed an update that (I hope) will take care of the issues. Can you try again?

**Comment by slonik-az** [comment]
Hi @ndphillips : Unfortunately, no luck. ToothGrowth still missed 'index' column (which I fixed).
Now I am getting:
```
Quitting from lines 5639-5656 (YaRrr.Rmd) 
Error in plot.xy(xy.coords(x, y), type = type, ...) : 
  object 'google.colors' not found
Calls: <Anonymous> ... eval -> eval -> points -> points.default -> plot.xy
Execution halted
Exited with status 1.
```
The offending code is:
```{r fig.width = 6, fig.height = 4}
plot(1, 
     xlim = c(0, 7), 
     ylim = c(0, 1),
     type = "n", 
     main = "Using colors stolen from a webpage")

points(x = 1:6, 
       y = rep(.4, 6),
       pch = 16,
       col = google.colors[c(1, 2, 3, 1, 4, 2)],
       cex = 4)

text(x = 1:6, 
     y = rep(.7, 6),
     labels = c("G", "O", "O", "G", "L", "E"), 
     col = google.col[c(1, 2, 3, 1, 4, 2)],
     cex = 3)
```
where is `google.colors` defined?

-- Leo

**Comment by slonik-az** [comment]
@ndphillips : I seem to fixed the problems. Please, see my pull request
