### ISSUE TITLE
Figure Numbers

### ISSUE THREAD

**Issue by nmoorenz** [ndphillips/ThePiratesGuideToR#14]
The figure numbers seem like they are aligned to section/chapter numbers, apart from chapter 2, which continue on as 1.x. From chapter 3 onwards these are 3.x and 4.x etc.

**Comment by ndphillips** [comment]
Hmm, I wonder if this was a bookdown issue. I've re-rendered the site and it looks ok now. See screenshot below. Thanks for flagging though!
![image](https://github.com/user-attachments/assets/a1148b21-1766-4dd3-a022-0049613275d4)
