### ISSUE TITLE
Error in library(yarrr) : there is no package called ‘yarrr’

### ISSUE THREAD

**Issue by arteteco** [ndphillips/ThePiratesGuideToR#16]
Hello,
I just started this book. Installing the yarrr packages with `install.packages('yarrr')` goes somewhere but I seem to have this two warning messages at the end:

```
Warning messages:
1: In install.packages("yarrr") :
  installation of package ‘BayesFactor’ had non-zero exit status
2: In install.packages("yarrr") :
  installation of package ‘yarrr’ had non-zero exit status

```

Upon loading the library seems like it's not there

```
> library(yarrr)
Error in library(yarrr) : there is no package called ‘yarrr’
```

R version 3.3.3
Debian 9

Hope this helps, I don't think I'm missing something, I mean those are the very first two commands to use =D

**Comment by ndphillips** [comment]
Yep this is the notorious BayesFactor package issue. Just install it first with `install.packages("BayesFactor")` then try installing yarrr again, it should work!

**Comment by arteteco** [comment]
Seems like BayesFactor won't install, another unmet dependency which is not satisfied even with `dependencies = TRUE`. Guess I should ask to the BayesFactor people, but for documentation I'll paste the error here too.

Thanks!

```
> install.packages("BayesFactor")
Installing package into ‘/home/tombom/R/x86_64-pc-linux-gnu-library/3.3’
(as ‘lib’ is unspecified)
Warning: dependency ‘mvtnorm’ is not available
trying URL 'https://cran.stat.unipd.it/src/contrib/BayesFactor_0.9.12-4.2.tar.gz'
Content type 'application/octet-stream' length 3779186 bytes (3.6 MB)
==================================================
downloaded 3.6 MB

ERROR: dependency ‘mvtnorm’ is not available for package ‘BayesFactor’
* removing ‘/home/tombom/R/x86_64-pc-linux-gnu-library/3.3/BayesFactor’

The downloaded source packages are in
	‘/tmp/Rtmp48IgO6/downloaded_packages’
Warning message:
In install.packages("BayesFactor") :
  installation of package ‘BayesFactor’ had non-zero exit status

```

**Comment by ndphillips** [comment]
Closing as this appears to be a dependency issue. Please reopen if needed
