### ISSUE TITLE
Error in `aggregate.formula()`

### ISSUE THREAD

**Issue by pstils** [ndphillips/ThePiratesGuideToR#26]
`Quitting from lines 631-635 [unnamed-chunk-37] (YaRrr.Rmd)
Error in `aggregate.formula()`:
! argument 'x' is  missing -- it has been renamed from 'formula'
Backtrace:
 1. stats::aggregate(formula = age ~ sex, data = pirates, FUN = mean)
 2. stats:::aggregate.formula(...)`

I'm running the line: 

`Rscript -e "bookdown::render_book('index.Rmd', 'bookdown::gitbook')"`

Trying to get the book to compile. 

Thanks,

**Comment by ndphillips** [comment]
This should now be fixed in https://github.com/ndphillips/ThePiratesGuideToR/commit/614f97172583bd81917108b899258b5e7df9b135
