### ISSUE TITLE
Mistake in question

### ISSUE THREAD

**Issue by lightpollutions** [ndphillips/ThePiratesGuideToR#27]
The intro page to chapter 7
asks
" # What percent of boats were older than 100 years old?"
and answers 
"mean(boat.ages < 100)
## [1] 0.6"
really it should be 
mean(boat.ages > 100)
or the question should be younger than 100

**Comment by ndphillips** [comment]
Great catch @lightpollutions , It's been fixed in https://github.com/ndphillips/ThePiratesGuideToR/commit/e3812567270fa25523f2b149ae529a14b8c74ab1 and should be published shortly
