### ISSUE TITLE
Typo in the preface

### ISSUE THREAD

**Issue by kebien6020** [ndphillips/ThePiratesGuideToR#3]
There is a typo in the preface, specifically in section 1.3 Why is R so great? where it says

> 2. R is the *presnt*, and future of statistical programming.

**Comment by negin1986** [comment]
The following link in the book does not work for me:
R Basics by Mhairi McNeill 
http://github.com/rstudio/cheatsheets/raw/master/source/pdfs/base-r.pdf

**Comment by negin1986** [comment]
Also, this sentence:
"To download and install RStudio (around 40mb), go to one of the links above and follow the instructions." I guess it should be go to the link below because the links above are only for R not R studio.

**Comment by negin1986** [comment]
In the Part 2.3 (Packages) of the book below the figure 1.12, the sentence below:
Figure 1.12: An R package is light a lightbulb. 

An R package is LIKE a lightbulb.

**Comment by ndphillips** [comment]
Thanks for catching these! Pushing updates now :)

**Comment by negin1986** [comment]
No problem! Nice book though :)
